const COLORS = {
  "Coal": "#252A2B",
  "NGCC": "#6D7374",
  "NGCT": "#C0C6C8",
  "NG CC": "#6D7374",
  "NG GT": "#C0C6C8",
  "Storage": "#E82269",
  "UtilStorage": "#E82269",
  "Nuclear": "#814DB1",
  "Hydro": "#003FFD",
  "Wind": "#2CA02C",
  "Offshore": "#98DF8A",
  "DPV": "#FF7F0E",
  "UPV": "#FFDE20",
  "CSP": "#FDFD4D",
  "Geo/Bio": "#8C564B",
  "CCS": "#D62728",
  "SMR": "#0DC3A8",
  "ARTES": "#0DC3A8",
  "HTGR": "#0DC3A8"
};
const TN = {
  "Coal": "Coal",
  "NGCC": "Natural Gas CC",
  "NGCT": "Natural Gas CT",
  "NG CC": "Natural Gas CC",
  "NG GT": "Natural Gas CT",
  "Storage": "Battery Storage",
  "UtilStorage": "Battery Storage",
  "Nuclear": "Nuclear",
  "Hydro": "Hydro",
  "Wind": "Onshore Wind",
  "Offshore": "Offshore Wind",
  "DPV": "Rooftop Solar",
  "UPV": "Utility Solar",
  "CSP": "CSP",
  "Geo/Bio": "Geo/Bio",
  "CCS": "CCS",
  "SMR": "Advanced Nuclear",
  "ARTES": "Advanced Nuclear",
  "HTGR": "Advanced Nuclear"
};
const CC = {
  "NG CC": "#6D7374",
  "NG GT": "#C0C6C8",
  UtilStorage: "#E82269",
  Nuclear: "#814DB1",
  Hydro: "#003FFD",
  Wind: "#2CA02C",
  Offshore: "#98DF8A",
  DPV: "#FF7F0E",
  UPV: "#FFDE20",
  "Geo/Bio": "#8C564B",
  CCS: "#D62728",
  SMR: "#0DC3A8",
  ARTES: "#0DC3A8",
  HTGR: "#0DC3A8",
  "Advanced Nuclear": "#0DC3A8",
  Coal: "#252A2B"
};
const YEARS = [2020, 2025, 2030, 2035, 2040, 2045, 2050],
  AT = Object.keys(COLORS);
const N2A = {
  "Alabama": "AL",
  "Alaska": "AK",
  "Arizona": "AZ",
  "Arkansas": "AR",
  "California": "CA",
  "Colorado": "CO",
  "Connecticut": "CT",
  "Delaware": "DE",
  "Florida": "FL",
  "Georgia": "GA",
  "Hawaii": "HI",
  "Idaho": "ID",
  "Illinois": "IL",
  "Indiana": "IN",
  "Iowa": "IA",
  "Kansas": "KS",
  "Kentucky": "KY",
  "Louisiana": "LA",
  "Maine": "ME",
  "Maryland": "MD",
  "Massachusetts": "MA",
  "Michigan": "MI",
  "Minnesota": "MN",
  "Mississippi": "MS",
  "Missouri": "MO",
  "Montana": "MT",
  "Nebraska": "NE",
  "Nevada": "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  "Ohio": "OH",
  "Oklahoma": "OK",
  "Oregon": "OR",
  "Pennsylvania": "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  "Tennessee": "TN",
  "Texas": "TX",
  "Utah": "UT",
  "Vermont": "VT",
  "Virginia": "VA",
  "Washington": "WA",
  "West Virginia": "WV",
  "Wisconsin": "WI",
  "Wyoming": "WY",
  "District of Columbia": "DC",
  "Puerto Rico": "PR"
};

const BAN_STATES = ["CA", "CT", "HI", "MA", "ME", "MN", "NJ", "OR", "RI", "VT"];

let map, gL, uL, cL, sL, cY = "2020",
  cS = "LowCost LowLR",
  cT = "map",
  cSt = "California",
  aT = new Set(["Nuclear", "SMR", "ARTES", "HTGR"]),
  aI = null,
  showUprate = true,
  showConvert = true;
let ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, chNucCap, chJobs, chNucShare, chNucEnergy, sC = "reactors",
  sA = false;

